name: rl
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  # Core
  - python=3.10
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - jinja2
  - requests
  - psutil
  - tqdm
  - tk

  # PyTorch (GPU build). Requires a working NVIDIA driver.
  - pytorch
  - pytorch-cuda=12.1  # <-- comment this line if you want CPU-only

  # Useful extras
  - joblib
  - rich
  - box2d-py
  - pandas-stubs
  -
  # Testing
  - pytest            # The core testing framework
  - pytest-cov        # For measuring code coverage
  - pytest-mock       # For mocking environment interactions

  - pip:
      - gymnasium==1.2.0
      - stable-baselines3==2.7.0
      - yfinance==0.2.66
      - stockstats==0.6.5
      - finrl==0.3.7
      - ale-py==0.11.2
      - moviepy==2.2.1
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - pygame==2.6.1
      - opencv-python==4.12.0.88
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - absl-py==2.3.1
      - protobuf==6.32.0
      - cloudpickle==3.1.1
      - beautifulsoup4==4.13.5
      - websockets==15.0.1
      - werkzeug==3.1.3
      - python-dotenv==1.1.1

